SH_DIR=${HOME}/dotfiles/sh
[ -f ${SH_DIR}/bootfuncs.bashrc ] && . ${SH_DIR}/bootfuncs.bashrc

load_optional /etc/profile
load_optional /etc/bashrc
load_optional $HOME/.bashrc.bak

. ${SH_DIR}/main.bashrc

eval "$(mise activate bash)"
eval "$(direnv hook bash)";

BASHRC_DIR=${HOME}/dotfiles/bash
. ${BASHRC_DIR}/prompt.bashrc

. $HOME/dotfiles/.fzf.bash

load_optional ${BASHRC_DIR}/$(uname).bashrc
load_optional ${BASHRC_DIR}/local.bashrc

alias reload='. ~/.bashrc'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
eval "$(/home/masumikanai.linux/.local/bin/mise activate bash)"
