SH_DIR=${HOME}/dotfiles/sh
[ -f ${SH_DIR}/bootfuncs.bashrc ] && . ${SH_DIR}/bootfuncs.bashrc

load_optional $HOME/powerlevel10k/powerlevel10k.zsh-theme

. ${SH_DIR}/main.bashrc

bindkey -e

alias reload='. ~/.zshrc'

load_optional $HOME/dotfiles/.fzf.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
