[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'vim-scripts/ShowMarks7'

[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/vimfiler'
depends = ['Shougo/unite.vim']
[[plugins]]
repo = 'taka84u9/unite-git'
depends = ['Shougo/unite.vim']
[[plugins]]
repo = 'majutsushi/tagbar'
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'yuku-t/vim-ref-ri'
depends = ['thinca/vim-ref']

[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'c9s/cascading.vim'
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
[[plugins]]
repo = 'dgryski/vim-godef'
on_ft = 'go'
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'
[[plugins]]
repo = 'mattn/emmet-vim'
