[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup = 1
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depents = ['Shougo/context_filetype.vim']
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
call denite#custom#map('insert', '<Down>', '<denite:move_to_next_line>', 'noremap')
call denite#custom#map('insert', '<Up>', '<denite:move_to_previous_line>', 'noremap')

nnoremap <silent> <C-u>f :<C-u>DeniteBufferDir file_rec<CR>
nnoremap <silent> <C-u>F :<C-u>Denite file_rec<CR>
nnoremap <silent> <C-u>b :<C-u>Denite buffer<CR>
nnoremap <silent> <C-u>w :<C-u>Denite line<CR>
nnoremap <silent> <C-u>c :<C-u>DeniteCursorWord line<CR>
nnoremap <silent> <C-u>g :<C-u>Denite grep<CR>
nnoremap <silent> <C-u>G :<C-u>DeniteBufferDir grep<CR>
nnoremap <silent> <C-u>l :<C-u>DeniteCursorWord grep<CR>
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
depends = [ 'Shougo/unite.vim', 'Shougo/denite.nvim' ]
hook_add = '''
nnoremap <silent> <C-u>o :<C-u>Denite unite:outline<CR>
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'jacquesbh/vim-showmarks'
hook_add = '''
aug show-marks-sync
  au!
  au BufReadPost * sil! DoShowMarks
aug END

nnoremap [Mark] <Nop>
nmap     m [Mark]

if !exists('g:markrement_char')
  let g:markrement_char = [
    \   'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
    \   'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'
    \ ]
endif
nnoremap <silent>[Mark]m :<C-u>call <SID>AutoMarkrement()<CR>:DoShowMarks<CR>
function! s:AutoMarkrement()
  if !exists('b:markrement_pos')
    let b:markrement_pos = 0
  else
    let b:markrement_pos = (b:markrement_pos + 1) % len(g:markrement_char)
  endif
  execute 'mark' g:markrement_char[b:markrement_pos]
  echo 'marked' g:markrement_char[b:markrement_pos]
endfunction
command! -nargs=? SetNextMarkChar call s:set_next_mark_char(<f-args>)
function! s:set_next_mark_char(...)
  if a:0 >= 1
    let b:markrement_pos=index(g:markrement_char,a:1)-1
  else
    echo "Next:".g:markrement_char[b:markrement_pos+1]
  end
endfunction
for m in g:markrement_char
  execute 'nnoremap [Mark]s'.m ':SetNextMarkChar '.m.'<CR>'
  execute 'nnoremap [Mark]f'.m ':SetNextMarkChar '.m.'<CR>:<C-u>call <SID>AutoMarkrement()<CR>:DoShowMarks<CR>'
endfor

nnoremap [Mark]n ]`
nnoremap [Mark]p [`
" show mark list
nnoremap [Mark]l :<C-u>PreviewMarks<CR>
" delete all marks
command! -bar MarksDelete sil :delm! | :delm 0-9A-Z | :wv! | :DoShowMarks
nnoremap <silent>[Mark]d :MarksDelete<CR>
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <silent> <Leader>gf   :Gfetch<CR>
nnoremap <silent> <Leader>diff :Gdiff<CR>
'''

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
nnoremap <Leader>ff :vs +Vaffle<CR>
'''
# [[plugins]]
# repo = 'Shougo/vimfiler'
# depends = ['Shougo/unite.vim']

## [[plugins]]
## repo = 'unite-giti'
## depends = ['Shougo/denite.nvim']
## hook_add = '''
## """ nnoremap <Leader>le :Denite unite:git_modified<CR>
## """ nnoremap <Leader>lu :Denite unite:git_untracked<CR>
## """ nnoremap <Leader>lc :Denite unite:git_cached<CR>
## """ nnoremap <Leader>ld :Denite unite:gtags/def<CR>
## """ nnoremap <Leader>cf :Denite unite:filetype<CR>
## '''

[[plugins]]
repo = 'majutsushi/tagbar'

# [[plugins]]
# repo = 'thinca/vim-ref'
# [[plugins]]
# repo = 'yuku-t/vim-ref-ri'
# depends = ['thinca/vim-ref']

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
" jellybeans, wombat, molokai
let g:lightline = {
  \ 'colorscheme': 'jellybeans',
  \ 'active': {
  \   'left': [
  \     ['mode', 'paste'],
  \     ['readonly', 'filename', 'modified', 'ale'],
  \   ]
  \ },
  \ 'component_function': {
  \   'ale': 'ALEGetStatusLine'
  \ }
  \ }
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
nmap <silent> <C-n> <Plug>(ale_toggle)
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
nmap <silent> <C-l> <Plug>(ale_first)
nmap <silent> <C-h> <Plug>(ale_last)

let g:ale_enabled = 0
let g:ale_lint_on_save = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error   = '✗'
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['✗ %d', '⚠ %d', '⬥ ok']
let g:ale_echo_msg_error_str   = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_open_list = 1
let g:ale_set_quickfix = 0

let g:ale_linters = {'go': ['gofmt', 'goimports', 'golint', 'go vet', 'gometalinter']}
let g:ale_go_gometalinter_options = '--fast --enable=staticcheck --enable=gosimple --enable=unused'
'''

[[plugins]]
repo = 'fatih/vim-go'
# on_ft = ['go']
hook_add = '''
let g:go_def_mapping_enabled = 0
let g:go_template_autocreate = 1
let g:go_template_file = "hello_world.go"

let g:go_auto_sameids = 0   " too heavy
let g:go_auto_type_info = 0 " too heavy
let g:go_info_mode = 'gocode'
let g:go_updatetime = 200

let g:go_doc_keywordprg_enabled = 1 "change K(keywordprg) to :GoDoc
let g:go_doc_max_height = 20
let g:go_autodetect_gopath = 1 " 迷ってる, _vendor, vendor共に対応できるか検証してから

let g:go_list_type = "quickfix"
let g:go_fmt_autosave = 1
let g:go_fmt_command = 'goimports'
let g:go_metalinter_autosave = 0

let g:go_addtags_transform = 'snakecase'
let g:go_snippet_engine = "neosnippet"

let g:go_textobj_enabled = 1
let g:go_textobj_include_function_doc = 1
'''

[[plugins]]
repo = 'dgryski/vim-godef'
on_ft = ['go']
hook_source = '''
let g:godef_split=1
let g:godef_same_file_in_same_window=0
'''

[[plugins]]
repo = 'mattn/sonictemplate-vim'
depends = [ 'Shougo/unite.vim', 'Shougo/denite.nvim' ]
hook_add = '''
nnoremap <silent> <C-u>t :<C-u>Denite unite:sonictemplate<CR>
let g:sonictemplate_vim_template_dir = [
  \ '$HOME/.vim/template',
  \]
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
imap <expr><tab> pumvisible() ? "\<C-n>" :
  \ neosnippet#expandable_or_jumpable() ?
  \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
call deoplete#custom#set('_', 'converters', ['converter_auto_paren'])
imap <expr><CR> neosnippet#expandable() ? "\<Plug>(neosnippet_expand)" : "\<CR>"
'''

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = ''' !has('nvim') '''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = ''' !has('nvim') '''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
depends = [ 'Shougo/deoplete.nvim' ]

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = [ 'Shougo/deoplete.nvim' ]

[[plugins]]
repo = 'vim-scripts/pydoc.vim'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
depends = [ 'Shougo/deoplete.nvim' ]

[[plugins]]
repo = 'Shougo/neco-vim'
depends = [ 'Shougo/deoplete.nvim' ]

# [[plugins]]
# repo = 'mattn/emmet-vim'
# 
# 

# [[plugins]]
# repo = 'vim-scripts/errormarker.vim'
# hook_add = '''
# let &errorformat="%f:%l:%c: %t%*[^:]:%m,%f:%l: %t%*[^:]:%m," . &errorformat
# '''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = '''
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
'''
depends = [ 'neosnippet-snippets' ]

# 
# 
# 
# [[plugins]]
# repo = 'vim-utils/vim-man'
# 
# [[plugins]]
# repo = 'rust-lang/rust.vim'
# [[plugins]]
# repo = 'racer-rust/vim-racer'
