- hosts: macbook
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - {name: caskroom/homebrew-versions, state: absent}
      - caskroom/cask
    homebrew_packages:
      - ansible
      - curl
      - cmake
      - ctags
      - make
      - gist
      - git
      - git-flow
      - libxml2
      - lv
      - openssl
      - {name: openssl, state: linked, install_options: force }
      - peco
      - pssh
      - readline
      - rlwrap
      - screen
      - tree
      - tmux
      - vim
      - wget

      - python
      - python3
      - pypy
    homebrew_cask_packages:
      # - alfred
      # - clamxav
      - firefox-ja
      - google-chrome
      - google-hangouts
      - google-web-designer
      - xtrafinder

      - virtualbox
      - vagrant
      - iterm2
      - xquartz
      - wireshark

      - atom
      - sublime-text
      - visual-studio-code
      - lighttable
      - kobito

      - skype
      # - limechat
      - cyberduck
      - dropbox
      - google-drive
      # - evernote
      # - skitch
  tasks:
    - name: 基本的なdirを作る
      file: path={{ item }} state=directory
      with_items: [ ~/works, ~/.local/bin, ~/local/bin, ~/local/lib, ~/local/doc ]
    - name: dotfiles のlinkを作成する
      file: src=~/dotfiles/{{ item }} path=~/{{ item }} state=link
      with_items: [ .ackrc, .bashrc, .gitconfig, .inputrc, .screenrc, .tmux.conf, .vim, .vimrc, .zshrc ]
    - name: .bash_profile に内容を追記する
      lineinfile:
        dest: '~/.bash_profile'
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
        insertafter: '{{ item.insertafter }}'
      with_items:
        - line: 'export HOMEBREW_CASK_OPTS="$HOMEBREW_CASK_OPTS --appdir=/Applications"'
          regexp: 'export HOMEBREW_CASK_OPTS="(\$HOMEBREW_CASK_OPTS *)?--appdir=/Applications"'
          insertafter: 'export HOMEBREW_CASK_OPTS=.*'
        - line: '. ~/.bashrc'
          regexp: '\. ~/.bashrc'
          insertafter: EOF
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item.name|default(item) }} state={{ item.state|default('present') }}
      with_items: homebrew_taps
    # - name: homebrew をアップデート
    #   homebrew: update_homebrew=yes
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name|default(item) }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: brew パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    # - name: brew パッケージの情報を保存
    #   shell: brew info {{ item }} > brew_info/{{ item }}
    #   with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    - name: homebrew-cask のインストール
      homebrew: name=brew-cask state=latest
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name|default(item) }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    # - name: cask パッケージの情報を保存
    #   shell: brew cask info {{ item }} > cask_info/{{ item }}
    #   with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
    - name: Python開発用環境を作成
      pip: name={{ item }}
      with_items: [ virtualenv, virtualenvwrapper, pipsi ]
    - name: pipsiでツール類をインストール
      shell: pipsi install {{ item }}
      with_items: [ vim-vint ]
    - name: OSXのFinderの設定を変更する
      shell: defaults write com.apple.finder AppleShowAllFiles TRUE
